### ISSUE TITLE
Add the plugin name and version info as a request agent

### ISSUE THREAD

**Issue by kunny** [cocos/cocos-google-admob#1]
Please add the plugin name and version info as a request agent in the ad request to help measure the plugin usage statistics and performance. You can use the following method for setting the request agent:
* Android: [AdRequest.Builder.setRequestAgent()](https://developers.google.com/android/reference/com/google/android/gms/ads/AdRequest.Builder#setRequestAgent(java.lang.String))
* iOS: [GADRequest request](https://developers.google.com/admob/ios/api/reference/Classes/GADRequest#requestagent)

Recommended request pattern is `cocos-x.y.z`. Please refer to the [official Unity plugin's implementation](https://github.com/googleads/googleads-mobile-unity/blob/main/source/plugin/Assets/GoogleMobileAds/Api/Core/AdRequest.cs#L72) for your reference.

For example, if the plugin version is `1.0.1`, the request agent string should be `cocos-1.0.1`.

**Comment by UniqueDisplayNameIsInUse** [comment]
Done
