### ISSUE TITLE
Banner is rendered outside of Safe area (iOS)

### ISSUE THREAD

**Issue by kunny** [cocos/cocos-google-admob#13]
The banner is rendered outside of Safe Area on iOS devices, causing the banner clipped due to display cutout (notch / dynamic island) area.

Please refer to the [GMA Unity Plugin](https://github.com/googleads/googleads-mobile-unity/blob/main/source/plugin/Assets/Plugins/iOS/GADUPluginUtil.m#L78)'s implementation for your reference.

**Comment by W-MTZing** [comment]
fix in #14, please verify it

**Comment by kunny** [comment]
Confirmed #14 fixed the issue. Thanks!
