### ISSUE TITLE
iOS ad request does not include the request agent string

### ISSUE THREAD

**Issue by kunny** [cocos/cocos-google-admob#15]
Ad requests sent on iOS is missing the plugin name and version info (`cocos-x.y.z`), which should be configured as a request agent string.

On Android, [AdServiceHub.extensionVersion](https://github.com/cocos/cocos-google-admob/blob/main/extensions/GoogleAdMob/template/android/libadmob/src/com/cocos/admob/AdServiceHub.java#L44) exposes the plugin name and version, and the request agent string is being configured in services for each ad format. (e.g., [AppOpenAdService](https://github.com/cocos/cocos-google-admob/blob/main/extensions/GoogleAdMob/template/android/libadmob/src/com/cocos/admob/service/AppOpenAdService.java#L84))

It seems [AdServiceHub on iOS](https://github.com/cocos/cocos-google-admob/blob/main/extensions/GoogleAdMob/template/ios/admob/AdServiceHub.m) does not have the `extensionVersion` field, and [not configuring the request agent](https://github.com/cocos/cocos-google-admob/blob/main/extensions/GoogleAdMob/template/ios/admob/service/AppOpenAdService.m#L94) string as well.

**Comment by W-MTZing** [comment]
Thanks, fix in #17 please verify it

**Comment by kunny** [comment]
Confirmed request agent string (`cocos-1.0.1`) is included in all ad requests. Thanks!
