### ISSUE TITLE
Banner is rendered outside of Safe area

### ISSUE THREAD

**Issue by kunny** [cocos/cocos-google-admob#3]
While checking the implementations being worked on #2, I noticed that the banner is rendered outside of Safe area, causing the banner become clipped due to display cutout (notch or punch hole).

I think the extension should respect the display cutout when rendering the banner similar to [GMA Unity plugin](https://github.com/googleads/googleads-mobile-unity/blob/main/source/android-library/app/src/main/java/com/google/unity/ads/Banner.java#L488) does.

**Comment by UniqueDisplayNameIsInUse** [comment]
Fixed.

Use getDisplayCutout to get a safe area. If the Android SDK version is below 23, returns zero.

**Comment by kunny** [comment]
Confirmed the banner is displayed within the Safe area. Tested on Pixel 6 Pro. Thanks!
